# Generated by Django 4.0.1 on 2022-01-25 09:37

from django.db import migrations, models

from markets.gen_master_data import gen_master


class Migration(migrations.Migration):
    dependencies = [
        ('markets', '0002_alter_market_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='review_point',
            field=models.FloatField(default=0, verbose_name='리뷰평점'),
        ),
        migrations.RunPython(gen_master),
    ]
