# Generated by Django 4.0.1 on 2022-01-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': '회원들', 'verbose_name_plural': '회원'},
        ),
    ]
