# Generated by Django 4.0.1 on 2022-01-20 12:03

from django.db import migrations, models
import django.db.models.expressions

from products.gen_master_data import gen_master


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_alter_product_product_picked_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AddConstraint(
            model_name='productreal',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('product'), django.db.models.expressions.F('option_1_name'), django.db.models.expressions.F('option_2_name'), django.db.models.expressions.F('option_3_name'), name='option_name_unique'),
        ),
        migrations.RunPython(gen_master),
    ]
